import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";
import { defineConfig, globalIgnores } from "eslint/config";

export default defineConfig([
  globalIgnores([
    "dist",
    "coverage",
    ".old",
    ".v2-extras",
    "public",
    "src/routeTree.gen.ts",
  ]),
  {
    files: ["**/*.{ts,tsx}"],
    extends: [
      js.configs.recommended,
      tseslint.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    rules: {
      // Underscore prefix is the project convention for intentionally
      // unused parameters / catch bindings / destructured holes.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
        },
      ],
      // TanStack Router file-routes export `Route = createFileRoute(...)({…})`
      // and colocate the component the route renders. Tag `createFileRoute`
      // as a HOC so the plugin sees Route as a component export and stops
      // warning about the colocated component. `allowExportNames` is NOT used
      // here because it short-circuits before the HOC check and would leave
      // the route's local component flagged.
      "react-refresh/only-export-components": [
        "error",
        {
          allowConstantExport: true,
          // shadcn theme-provider co-exports the `useTheme` hook with the
          // provider component — explicit allow keeps the pattern intact.
          allowExportNames: ["useTheme"],
        },
      ],
    },
  },
  {
    // shadcn-generated UI primitives co-export variants (cva), contexts,
    // and helper hooks next to the component. Fast-Refresh restrictions
    // don't apply to these — they're auto-regenerated by `shadcn add`,
    // not hand-edited during HMR sessions.
    files: ["src/components/ui/**/*.{ts,tsx}"],
    rules: {
      "react-refresh/only-export-components": "off",
    },
  },
  {
    // TanStack Router file-routes idiomatically co-export `Route` (object
    // returned by `createFileRoute`/`createRootRoute`) with the route's
    // component. `createFileRoute` is NOT a React HOC — gaming it via
    // `extraHOCs` makes the rule pass but the eslint-plugin-react-refresh
    // maintainer warns it can degrade HMR over time. Disable the rule for
    // the routes directory instead; route files are small and visually
    // distinct, so the Fast-Refresh signal isn't pulling weight here.
    files: ["src/routes/**/*.{ts,tsx}"],
    rules: {
      "react-refresh/only-export-components": "off",
    },
  },
  {
    files: ["src/components/metric-evidence-table.tsx"],
    rules: {
      "react-hooks/incompatible-library": "off",
    },
  },
  {
    // Keep the text scale from growing back.
    //
    // It had drifted to twelve sizes and five greys, and none of that was
    // decided — each one was a reasonable local choice that nobody could see
    // the sum of. A reader learns a screen by learning its rules, and twelve
    // sizes with no rule behind them is not a hierarchy, it is decoration.
    //
    // So the sizes a screen may use are the ones in `src/lib/type-scale.ts`,
    // and a size written by hand is refused here rather than found later by
    // whoever measures it again. Fractional text greys go the same way: two
    // levels are readable as "read this / you may skip this", five are not
    // rankable by anyone and the rule stops holding.
    //
    // Vendored primitives under components/ui are exempt — their sizing is
    // that library's business and `shadcn add` rewrites them.
    files: ["src/**/*.tsx"],
    ignores: ["src/components/ui/**"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "Literal[value=/(^|\\s)text-\\[[0-9.]+(px|rem)\\]/]",
          message:
            "Hand-set text size. Use a role from src/lib/type-scale.ts, or add one there if none fits.",
        },
        {
          selector:
            "Literal[value=/(^|\\s)text-(muted-)?foreground\\/[0-9]/]",
          message:
            "Fractional text grey. There are two: text-foreground and text-muted-foreground.",
        },
        {
          selector: "Literal[value=/(^|\\s)text-(amber|red|green|emerald|rose|orange|yellow)-[0-9]/]",
          message:
            "Raw palette colour. Good/bad is text-success and text-destructive; text-warning is attention without a verdict.",
        },
      ],
    },
  },
]);
